#!/usr/bin/env python3
"""Generate the discoverability baseline artifacts from the Natural sources.

This is a *validation / generation harness* written in Python. It is not part
of any modernization target: it reads the shipped Natural objects through
``tools.analyze_disposition.analyze()`` and ``tests.harness.source_parser`` and
renders Markdown and Mermaid so that no count, edge, or object list in this
directory is hand-typed.

Outputs (all relative to this directory):

* ``module-inventory.md``          every object with type, LOC, executable LOC,
                                   callers, callees, DDM files touched, reach
                                   status, and the derived extraction waves
* ``diagrams/architecture.mmd``    library / layer view
* ``diagrams/call-graph.mmd``      CALLNAT / FETCH / INCLUDE edges
* ``diagrams/data-access.mmd``     code object -> ADABAS file with access verbs
* ``diagrams/README.md``           the same three diagrams embedded in Markdown
* ``discoverability-report.md``    hand-authored narrative; only the blocks
                                   between ``<!-- generated:NAME -->`` and
                                   ``<!-- /generated:NAME -->`` markers are
                                   rewritten (control totals, waves)

Usage::

    python3 fpps-hcm-modernization-deliverable/01-discoverability-comprehension-baseline/generate_inventory.py
    python3 fpps-hcm-modernization-deliverable/01-discoverability-comprehension-baseline/generate_inventory.py --check

``--check`` re-renders in memory and exits 1 if any committed output differs.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))

from tools.analyze_disposition import analyze  # noqa: E402
from tests.harness import source_parser as sp  # noqa: E402

CODE_TYPES = ("subprogram", "program", "copycode")
CALL_STATEMENTS = ("CALLNAT", "FETCH")
DB_OPEN_VERBS = ("READ", "FIND", "GET", "HISTOGRAM")
DB_WRITE_VERBS = ("STORE", "UPDATE", "DELETE")
DB_VERBS = DB_OPEN_VERBS + DB_WRITE_VERBS

_LABEL_ONLY = re.compile(r"^\s*([A-Z][A-Z0-9]*)\.\s*$")
_LABEL_INLINE = re.compile(r"^\s*([A-Z][A-Z0-9]*)\.\s+(.*)$")
_LABEL_REF = re.compile(r"\(\s*([A-Z][A-Z0-9]*)\.\s*\)")
_VIEW_DEF = re.compile(r"^\s*1\s+([A-Z0-9@#-]+)\s+VIEW\s+OF\s+([A-Z0-9@#-]+)", re.I)

OUTPUTS = {
    "module-inventory.md": HERE / "module-inventory.md",
    "diagrams/architecture.mmd": HERE / "diagrams" / "architecture.mmd",
    "diagrams/call-graph.mmd": HERE / "diagrams" / "call-graph.mmd",
    "diagrams/data-access.mmd": HERE / "diagrams" / "data-access.mmd",
    "diagrams/README.md": HERE / "diagrams" / "README.md",
    "discoverability-report.md": HERE / "discoverability-report.md",
}

GENERATED_BANNER = (
    "Generated by `python3 fpps-hcm-modernization-deliverable/"
    "01-discoverability-comprehension-baseline/generate_inventory.py` "
    "from `tools/analyze_disposition.py` and `tests/harness/source_parser.py`. "
    "**Do not edit by hand** — run the generator; `--check` fails CI-style if this file drifts."
)


# --------------------------------------------------------------------------
# data-access scan (view names in DB statements, label-aware)
# --------------------------------------------------------------------------
def _view_to_file(inventory):
    """Map every ``VIEW OF`` name declared in the LDAs to its DDM file name."""
    mapping = {}
    for obj in inventory:
        if obj["type"] != "local data area":
            continue
        for line in (REPO / obj["path"]).read_text(encoding="utf-8", errors="replace").splitlines():
            m = _VIEW_DEF.match(line)
            if m:
                mapping[m.group(1).upper()] = m.group(2).upper()
    return mapping


def _ddm_files(inventory):
    """DDM object name -> (ADABAS file name, db, fnr) via the harness DDM parser."""
    out = {}
    for obj in inventory:
        if obj["type"] == "DDM":
            ddm = sp.parse_ddm(REPO / obj["path"])
            out[obj["object"]] = (ddm.file_name, ddm.db, ddm.fnr)
    return out


def _db_access(path, view_to_file):
    """Return {file_name: sorted set of verbs} for one code object.

    Rules (static, conservative):
    * ``READ``/``FIND``/``GET``/``HISTOGRAM`` with a known view on the same
      line open that view; a preceding ``LABEL.`` (own line or inline) binds
      the label to the view.
    * ``STORE viewname`` names the view directly.
    * ``UPDATE (LABEL.)`` / ``DELETE (LABEL.)`` resolve through the label;
      an unlabelled ``UPDATE``/``DELETE`` is attributed to the most recently
      opened view (the innermost active loop in the shipped sources).
    * ``READ WORK`` lines carry no view and are ignored here (work files are
      reported in 06-interface-dependency-mapping instead).
    """
    lines = sp.strip_comments(sp.read_source(path))
    access = defaultdict(set)
    labels = {}
    pending_label = None
    last_view = None
    views = sorted(view_to_file, key=len, reverse=True)
    view_re = re.compile(r"\b(" + "|".join(re.escape(v) for v in views) + r")\b")

    for raw in lines:
        line = raw.upper()
        m = _LABEL_ONLY.match(line)
        if m:
            pending_label = m.group(1)
            continue
        m = _LABEL_INLINE.match(line)
        if m and re.match(r"^(READ|FIND|GET|HISTOGRAM)\b", m.group(2)):
            pending_label = m.group(1)
            line = m.group(2)
        verb_m = re.match(r"^\s*(READ|FIND|GET|HISTOGRAM|STORE|UPDATE|DELETE)\b(.*)$", line)
        if not verb_m:
            continue
        verb, rest = verb_m.group(1), verb_m.group(2)
        if verb == "READ" and re.match(r"^\s*WORK\b", rest):
            continue
        if verb in DB_OPEN_VERBS or verb == "STORE":
            vm = view_re.search(rest)
            if not vm:
                continue
            view = vm.group(1)
            fname = view_to_file[view]
            access[fname].add(verb)
            if verb in DB_OPEN_VERBS:
                last_view = fname
                if pending_label:
                    labels[pending_label] = fname
            pending_label = None
            continue
        # UPDATE / DELETE
        target = None
        lm = _LABEL_REF.search(rest)
        if lm:
            target = labels.get(lm.group(1))
        if target is None:
            vm = view_re.search(rest)
            target = view_to_file[vm.group(1)] if vm else last_view
        if target:
            access[target].add(verb)
    return {k: sorted(v, key=DB_VERBS.index) for k, v in access.items()}


# --------------------------------------------------------------------------
# model
# --------------------------------------------------------------------------
def build_model():
    result = analyze()
    inventory = sorted(result["inventory"], key=lambda o: (o["library"], o["type"], o["object"]))
    refs = result["references"]
    reach = {r["object"]: r for r in result["reachability"]}
    view_to_file = _view_to_file(inventory)
    ddm_files = _ddm_files(inventory)
    file_to_ddm = {v[0]: k for k, v in ddm_files.items()}

    callers = defaultdict(set)
    callees = defaultdict(list)
    for r in refs:
        callers[r["callee"]].add(r["caller"])
        callees[r["caller"]].append(r)

    access = {}
    for obj in inventory:
        if obj["type"] in ("subprogram", "program"):
            access[obj["object"]] = _db_access(REPO / obj["path"], view_to_file)

    ddm_touched_by = defaultdict(set)
    for obj, files in access.items():
        for fname in files:
            ddm_touched_by[file_to_ddm[fname]].add(obj)

    rows = []
    for obj in inventory:
        name = obj["object"]
        if obj["type"] == "DDM":
            c = sorted(ddm_touched_by[name])
            reach_status = "data file (accessed by " + str(len(c)) + " code objects)" if c else "unreferenced in analyzed scope"
        else:
            c = sorted(callers[name])
            reach_status = reach[name]["status"] if name in reach else "entry point (UI root)"
        rows.append({
            "object": name,
            "type": obj["type"],
            "library": obj["library"],
            "path": obj["path"],
            "lines": obj["lines"],
            "executable_lines": obj["executable_lines"],
            "callers": c,
            "callees": callees.get(name, []),
            "access": access.get(name, {}),
            "status": reach_status,
        })

    return {
        "result": result,
        "rows": rows,
        "refs": refs,
        "ddm_files": ddm_files,
        "file_to_ddm": file_to_ddm,
        "waves": _waves(rows, refs),
    }


def _waves(rows, refs):
    """Leaf-first extraction order over CALLNAT/FETCH edges between code objects.

    wave(x) = 1 + max(wave(callee)) over CALLNAT/FETCH callees; leaves are wave 1.
    Within a wave, read-only objects (no STORE/UPDATE/DELETE) precede writers,
    then alphabetical. Objects unreferenced in the analyzed scope and
    stand-alone programs are listed as candidates outside the waves.
    """
    by_name = {r["object"]: r for r in rows}
    code = {n for n, r in by_name.items() if r["type"] in ("subprogram", "program")}
    out_edges = defaultdict(set)
    for r in refs:
        if r["statement"] in CALL_STATEMENTS and r["caller"] in code and r["callee"] in code:
            out_edges[r["caller"]].add(r["callee"])

    memo = {}

    def wave(n, stack=()):
        if n in memo:
            return memo[n]
        if n in stack:
            return 1
        w = 1 + max((wave(c, stack + (n,)) for c in out_edges[n]), default=0)
        memo[n] = w
        return w

    in_scope = {n for n in code if "reachable" in by_name[n]["status"] or "entry point" in by_name[n]["status"]}
    waves = defaultdict(list)
    for n in in_scope:
        waves[wave(n)].append(n)

    def writes(n):
        return sum(1 for verbs in by_name[n]["access"].values() for v in verbs if v in DB_WRITE_VERBS)

    ordered = []
    for w in sorted(waves):
        ordered.append((w, sorted(waves[w], key=lambda n: (writes(n) > 0, writes(n), n))))
    candidates = sorted(code - in_scope)
    return {"waves": ordered, "candidates": candidates, "writes": {n: writes(n) for n in code}}


# --------------------------------------------------------------------------
# rendering helpers
# --------------------------------------------------------------------------
def _md_table(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        L.append("| " + " | ".join(str(c) for c in r) + " |")
    return L


def _code(s):
    return f"`{s}`"


def _fmt_callees(callees):
    if not callees:
        return "—"
    parts = []
    for r in sorted(callees, key=lambda r: (r["line"], r["callee"])):
        parts.append(f"{r['statement']} `{r['callee']}` (L{r['line']})")
    return "; ".join(parts)


def _fmt_access(access):
    if not access:
        return "—"
    return "; ".join(f"`{f}` ({', '.join(v)})" for f, v in sorted(access.items()))


def _exec_loc(v):
    return "n/a" if v is None else str(v)


def _node_id(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def render_inventory(model):
    rows, refs, ct = model["rows"], model["refs"], model["result"]["control_totals"]
    by_lib = defaultdict(list)
    for r in rows:
        by_lib[r["library"]].append(r)

    stmt_counts = defaultdict(int)
    for r in refs:
        stmt_counts[r["statement"]] += 1

    L = [
        "# Module inventory (generated)",
        "",
        GENERATED_BANNER,
        "",
        "> Static inventory of `SunnyIslands/Natural-Libraries/`. Reach status is a *static candidate*"
        " classification (\"unreferenced in analyzed scope\", \"reachable from UI root\"); it does not"
        " prove or disprove runtime use. Maturity: **Demonstrated** — every number below is recomputed"
        " from the shipped sources on each run.",
        "",
        "## Control totals",
        "",
    ]
    type_counts = defaultdict(int)
    for r in rows:
        type_counts[(r["library"], r["type"])] += 1
    L += _md_table(["Measure", "Value"], [
        ("Natural objects (both libraries)", ct["objects"]),
        ("Code objects (subprogram / program / copycode)", ct["code_objects"]),
        ("Static references (CALLNAT / FETCH / INCLUDE / USING)", ct["static_references"]),
        ("… of which CALLNAT", stmt_counts["CALLNAT"]),
        ("… of which FETCH", stmt_counts["FETCH"]),
        ("… of which INCLUDE", stmt_counts["INCLUDE"]),
        ("… of which USING", stmt_counts["USING"]),
        ("Dynamic invocations (`CALLNAT #VAR`, unresolvable statically)", ct["dynamic_invocations"]),
        ("Total source lines (all objects)", sum(r["lines"] for r in rows)),
        ("Executable lines (code objects, comments and blanks removed)",
         sum(r["executable_lines"] or 0 for r in rows if r["type"] in ("subprogram", "program"))),
        ("Objects unreferenced in analyzed scope", ", ".join(_code(o) for o in ct["unreferenced_objects"]) or "none"),
        ("Stand-alone programs with no UI path", ", ".join(_code(o) for o in ct["standalone_programs_no_ui_path"]) or "none"),
    ])
    L += ["", "## Objects per library and type", ""]
    L += _md_table(["Library", "Object type", "Count"],
                   [(lib, t, n) for (lib, t), n in sorted(type_counts.items())])

    for lib in sorted(by_lib):
        L += ["", f"## `{lib}`", ""]
        L += _md_table(
            ["Object", "Type", "LOC", "Exec LOC", "Callers", "Callees (statement `callee` Lline)", "DDM files touched (verbs)", "Reach status"],
            [(
                _code(r["object"]), r["type"], r["lines"], _exec_loc(r["executable_lines"]),
                ", ".join(_code(c) for c in r["callers"]) or "—",
                _fmt_callees(r["callees"]),
                _fmt_access(r["access"]) if r["type"] in ("subprogram", "program") else "—",
                r["status"],
            ) for r in by_lib[lib]],
        )

    L += ["", "## ADABAS files (DDMs) and the code that touches them", ""]
    ddm_rows = []
    for ddm, (fname, db, fnr) in sorted(model["ddm_files"].items()):
        touch = defaultdict(list)
        for r in rows:
            if fname in r["access"]:
                touch[r["object"]] = r["access"][fname]
        ddm_rows.append((
            _code(ddm), _code(fname), db, fnr,
            "; ".join(f"`{o}` ({', '.join(v)})" for o, v in sorted(touch.items())) or "none in analyzed scope",
        ))
    L += _md_table(["DDM object", "ADABAS file", "DB", "FNR", "Accessed by (verbs)"], ddm_rows)

    L += ["", "## Extraction waves (derived from the call graph)", "",
          "Wave = 1 + the longest CALLNAT/FETCH path down to a leaf; leaves are wave 1. Within a wave, read-only"
          " objects precede objects that STORE/UPDATE/DELETE, then alphabetical. Only objects reachable from the"
          " UI root are waved; the remainder are static retirement candidates pending SME confirmation.", ""]
    wave_rows = []
    for w, names in model["waves"]["waves"]:
        for n in names:
            r = next(x for x in rows if x["object"] == n)
            wave_rows.append((w, _code(n), r["type"], r["library"],
                              model["waves"]["writes"][n], _fmt_access(r["access"])))
    L += _md_table(["Wave", "Object", "Type", "Library", "Write verbs", "DDM files touched (verbs)"], wave_rows)
    L += ["", "Outside the waves (static candidates, evidence class: unreferenced in analyzed scope / no UI path):", ""]
    L += [f"- `{n}`" for n in model["waves"]["candidates"]]
    L += ["", "## Source paths", ""]
    L += _md_table(["Object", "Path"], [(_code(r["object"]), _code(r["path"])) for r in rows])
    return "\n".join(L) + "\n"


def render_call_graph(model):
    rows, refs = model["rows"], model["refs"]
    by_name = {r["object"]: r for r in rows}
    L = ["%% Generated by generate_inventory.py — CALLNAT / FETCH / INCLUDE edges (Demonstrated)",
         "flowchart TD",
         '  UI["NJX page rdcruisx.xml<br/>(Demonstrated)"]']
    for lib in ("RDCRUISE", "CRUISE16"):
        L.append(f'  subgraph {lib}["{lib} (Demonstrated)"]')
        for r in rows:
            if r["library"] == lib and r["type"] in CODE_TYPES:
                L.append(f'    {_node_id(r["object"])}["{r["object"]}<br/>{r["type"]}"]')
        L.append("  end")
    L.append("  UI -->|PROCESS PAGE| RDCRUISP")
    grouped = defaultdict(list)
    for r in refs:
        if r["statement"] != "USING":
            grouped[(r["caller"], r["callee"], r["statement"])].append(r["line"])
    for (caller, callee, stmt), lines in sorted(grouped.items(), key=lambda kv: (kv[0][0], min(kv[1]))):
        lines = sorted(lines)
        label = f"{stmt} L{lines[0]}" if len(lines) == 1 else f"{stmt} ×{len(lines)} L" + ",".join(str(n) for n in lines)
        L.append(f'  {_node_id(caller)} -->|{label}| {_node_id(callee)}')
    cands = [r["object"] for r in rows if r["type"] in CODE_TYPES and "unreferenced" in r["status"] or
             r["type"] in CODE_TYPES and "no UI path" in r["status"]]
    L.append("  classDef candidate stroke-dasharray: 5 5,stroke:#b00,color:#b00;")
    if cands:
        L.append("  class " + ",".join(_node_id(c) for c in cands) + " candidate;")
    L.append("  classDef entry fill:#e8f0fe,stroke:#1a56db;")
    L.append("  class RDCRUISP,UI entry;")
    return "\n".join(L) + "\n"


def render_data_access(model):
    rows = model["rows"]
    L = ["%% Generated by generate_inventory.py — code object → ADABAS file (Demonstrated)",
         "flowchart LR"]
    L.append('  subgraph code["Natural code objects with database statements (Demonstrated)"]')
    for r in rows:
        if r["access"]:
            L.append(f'    {_node_id(r["object"])}["{r["object"]}<br/>{r["library"]}"]')
    L.append("  end")
    L.append('  subgraph adabas["ADABAS files — DDMs, DB 12 (Demonstrated)"]')
    for ddm, (fname, db, fnr) in sorted(model["ddm_files"].items()):
        L.append(f'    {_node_id(fname)}[("{fname}<br/>DDM {ddm} · FNR {fnr}")]')
    L.append("  end")
    for r in rows:
        for fname, verbs in sorted(r["access"].items()):
            arrow = "==>" if any(v in DB_WRITE_VERBS for v in verbs) else "-->"
            L.append(f'  {_node_id(r["object"])} {arrow}|{", ".join(verbs)}| {_node_id(fname)}')
    L.append("  classDef candidate stroke-dasharray: 5 5,stroke:#b00,color:#b00;")
    cands = [r["object"] for r in rows if r["access"] and ("unreferenced" in r["status"] or "no UI path" in r["status"])]
    if cands:
        L.append("  class " + ",".join(_node_id(c) for c in cands) + " candidate;")
    return "\n".join(L) + "\n"


def render_architecture(model):
    rows, refs = model["rows"], model["refs"]
    by = defaultdict(list)
    for r in rows:
        by[(r["library"], r["type"])].append(r["object"])
    lib_edges = defaultdict(int)
    for r in refs:
        cl = next(x["library"] for x in rows if x["object"] == r["caller"])
        el = next(x["library"] for x in rows if x["object"] == r["callee"])
        lib_edges[(cl, el, r["statement"])] += 1
    L = ["%% Generated by generate_inventory.py — layered architecture (Demonstrated)",
         "flowchart TB",
         '  browser["Browser / NJX page rdcruisx.xml<br/>27 page events"]'.replace(
             "27", str(model["result"]["control_totals"]["ui_events_declared"])),
         '  subgraph pres["RDCRUISE — presentation library (Demonstrated; ≈ web FPPS presentation layer)"]']
    for t in ("program", "subprogram", "global data area", "local data area"):
        if ("RDCRUISE", t) in by:
            L.append(f'    RD_{_node_id(t)}["{t}s: {", ".join(by[("RDCRUISE", t)])}"]')
    L.append("  end")
    L.append('  subgraph svc["CRUISE16 — business-logic library (Demonstrated; ≈ FPPS core Natural service libraries)"]')
    for t in ("subprogram", "copycode", "parameter data area", "local data area"):
        if ("CRUISE16", t) in by:
            L.append(f'    CR_{_node_id(t)}["{t}s: {", ".join(by[("CRUISE16", t)])}"]')
    L.append("  end")
    L.append('  subgraph data["ADABAS DB 12 (Demonstrated; ≈ FPPS personnel-payroll data model)"]')
    L.append(f'    DDMS[("DDMs: {", ".join(by[("CRUISE16", "DDM")])}")]')
    L.append("  end")
    L.append('  ext["External touch-points<br/>work file CruiseDescriptions.txt · image files · nat: content objects"]')
    L.append("  browser -->|PROCESS PAGE / *PAGE-EVENT| RD_program")
    for (cl, el, st), n in sorted(lib_edges.items()):
        if cl == "RDCRUISE" and el == "CRUISE16":
            L.append(f"  RD_program -->|{st} ×{n}| CR_subprogram")
    L.append("  CR_subprogram -->|READ / FIND / GET / STORE / UPDATE| DDMS")
    L.append("  RD_subprogram -.->|READ WORK / EXPAND XCIOBJECTS| ext")
    return "\n".join(L) + "\n"


def render_diagrams_readme(model, arch, call, data):
    exports = []
    for stem in ("architecture", "call-graph", "data-access"):
        for ext in (".svg", ".png"):
            if (HERE / "diagrams" / f"{stem}{ext}").exists():
                exports.append(f"{stem}{ext}")
    L = ["# Diagrams (generated)", "", GENERATED_BANNER, "",
         "All three diagrams are **Demonstrated**: they are rendered from the analyzer output, not drawn."
         " Dashed red nodes are static candidates (unreferenced in analyzed scope or no UI path); they are"
         " not asserted to be unused at runtime.", ""]
    if exports:
        L += ["Exported images in this directory: " + ", ".join(f"`{e}`" for e in exports) + ".", ""]
    else:
        L += ["No exported images are checked in; render the `.mmd` sources with a Mermaid renderer.", ""]
    L += ["## Architecture (`architecture.mmd`)", "", "```mermaid", arch.rstrip(), "```", "",
          "## Call graph (`call-graph.mmd`)", "", "```mermaid", call.rstrip(), "```", "",
          "## Data-access map (`data-access.mmd`)", "", "```mermaid", data.rstrip(), "```", ""]
    return "\n".join(L)


def _control_totals_block(model):
    rows, ct = model["rows"], model["result"]["control_totals"]
    per_lib = defaultdict(lambda: defaultdict(int))
    for r in rows:
        per_lib[r["library"]][r["type"]] += 1
    L = _md_table(["Measure", "Value"], [
        ("Natural objects in `CRUISE16` + `RDCRUISE`", ct["objects"]),
        ("Code objects (subprogram / program / copycode)", ct["code_objects"]),
        ("Static references (CALLNAT / FETCH / INCLUDE / USING)", ct["static_references"]),
        ("Dynamic invocations (unresolvable statically)", ct["dynamic_invocations"]),
        ("Source lines, all objects", sum(r["lines"] for r in rows)),
        ("Executable lines, programs and subprograms", sum(r["executable_lines"] or 0 for r in rows if r["type"] in ("subprogram", "program"))),
        ("Page events declared in `rdcruisx.xml`", ct["ui_events_declared"]),
        ("Objects unreferenced in analyzed scope", ", ".join(_code(o) for o in ct["unreferenced_objects"]) or "none"),
        ("Stand-alone programs with no UI path", ", ".join(_code(o) for o in ct["standalone_programs_no_ui_path"]) or "none"),
    ])
    L += ["", "| Library | " + " | ".join(t for t in ("program", "subprogram", "copycode", "global data area", "local data area", "parameter data area", "DDM")) + " | Total |",
          "|---|---|---|---|---|---|---|---|---|"]
    for lib in sorted(per_lib):
        counts = [per_lib[lib][t] for t in ("program", "subprogram", "copycode", "global data area", "local data area", "parameter data area", "DDM")]
        L.append(f"| `{lib}` | " + " | ".join(str(c) for c in counts) + f" | {sum(counts)} |")
    return "\n".join(L)


def _waves_block(model):
    rows = {r["object"]: r for r in model["rows"]}
    L = _md_table(["Wave", "Objects (read-only first, then writers)", "Why this order"], [
        (w, ", ".join(f"`{n}`" for n in names),
         "leaf services: no CALLNAT/FETCH out-edges" if w == 1 else
         "calls only objects in earlier waves")
        for w, names in model["waves"]["waves"]])
    L += ["", "Static candidates outside the waves (evidence class in `module-inventory.md`): " +
          ", ".join(f"`{n}` ({rows[n]['status']})" for n in model["waves"]["candidates"]) + "."]
    return "\n".join(L)


def _inject_blocks(text, blocks):
    for name, body in blocks.items():
        start, end = f"<!-- generated:{name} -->", f"<!-- /generated:{name} -->"
        if start not in text or end not in text:
            raise SystemExit(f"discoverability-report.md is missing the {name} marker pair")
        head, rest = text.split(start, 1)
        _, tail = rest.split(end, 1)
        text = head + start + "\n" + body + "\n" + end + tail
    return text


def render_report(model):
    path = OUTPUTS["discoverability-report.md"]
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    return _inject_blocks(text, {"control-totals": _control_totals_block(model), "waves": _waves_block(model)})


def render_all():
    model = build_model()
    arch = render_architecture(model)
    call = render_call_graph(model)
    data = render_data_access(model)
    return {
        "module-inventory.md": render_inventory(model),
        "diagrams/architecture.mmd": arch,
        "diagrams/call-graph.mmd": call,
        "diagrams/data-access.mmd": data,
        "diagrams/README.md": render_diagrams_readme(model, arch, call, data),
        "discoverability-report.md": render_report(model),
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if committed outputs differ from a fresh render")
    args = ap.parse_args(argv)
    rendered = render_all()
    if args.check:
        drift = []
        for key, text in rendered.items():
            path = OUTPUTS[key]
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                drift.append(str(path.relative_to(REPO)))
        if drift:
            print("DRIFT: regenerate with generate_inventory.py:\n  " + "\n  ".join(drift))
            return 1
        print("OK: 01-discoverability-comprehension-baseline generated outputs are current")
        return 0
    for key, text in rendered.items():
        OUTPUTS[key].parent.mkdir(parents=True, exist_ok=True)
        OUTPUTS[key].write_text(text, encoding="utf-8")
        print("wrote", OUTPUTS[key].relative_to(REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
