#!/usr/bin/env python3
"""Generate the interface and dependency map from the Natural sources.

This is a *validation / generation harness* written in Python. It is not a
modernization target: it reads the shipped Natural objects and the NJX page
through ``tools.analyze_disposition.analyze()`` and
``tests.harness.source_parser`` and renders Markdown and Mermaid so that no
edge, line number, or event name in this directory is hand-typed.

Outputs (relative to this directory):

* ``dependency-map.md``                full edge list (caller, statement,
                                       callee, source line), fan-in / fan-out,
                                       external touch-points (work files,
                                       content objects, NJX event contract)
* ``diagrams/dependency-graph.mmd``    CALLNAT / FETCH / INCLUDE edges (control flow)
* ``diagrams/data-area-usage.mmd``     USING edges (code object -> GDA / LDA / PDA)
* ``diagrams/event-contract.mmd``      NJX page events -> adapter handlers -> services
* ``diagrams/README.md``               the generated diagrams embedded in Markdown

Usage::

    python3 fpps-hcm-modernization-deliverable/06-interface-dependency-mapping/generate_dependency_map.py
    python3 fpps-hcm-modernization-deliverable/06-interface-dependency-mapping/generate_dependency_map.py --check

``--check`` re-renders in memory and exits 1 if any committed output differs.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))

from tools.analyze_disposition import analyze, UI_ROOT, UI_XML  # noqa: E402
from tests.harness import source_parser as sp  # noqa: E402

STATEMENT_ORDER = ("CALLNAT", "FETCH", "INCLUDE", "USING")
CODE_TYPES = ("subprogram", "program", "copycode")

_WORK_RE = re.compile(r"^\s*(DEFINE WORK FILE|READ\s+WORK|CLOSE WORK|WRITE WORK|END-WORK)\b(.*)$", re.I)
_XCI_RE = re.compile(r"XCIOBJECTS")
_PAGE_RE = re.compile(r"^\s*(PROCESS PAGE(?: USING| UPDATE)?|DECIDE ON FIRST \*PAGE-EVENT)\b(.*)$", re.I)
_EVENT_HANDLER_RE = re.compile(r"VALUE\s+U?'((?:[a-z]+\.)?[A-Za-z0-9:.]+)'")
_XML_METHOD_RE = re.compile(r'\b(?:on[a-z]*)?method="(on[A-Za-z0-9]+)"')
_PERFORM_RE = re.compile(r"^\s*PERFORM\s+([A-Z0-9-]+)", re.I)
_SUBROUTINE_RE = re.compile(r"^\s*DEFINE SUBROUTINE\s+([A-Z0-9-]+)", re.I)
_CALLNAT_RE = re.compile(r"CALLNAT\s+['\"]([A-Z0-9-]+)['\"]", re.I)
_FETCH_RE = re.compile(r"FETCH(?:\s+RETURN)?\s+['\"]([A-Z0-9-]+)['\"]", re.I)

OUTPUTS = {
    "dependency-map.md": HERE / "dependency-map.md",
    "diagrams/dependency-graph.mmd": HERE / "diagrams" / "dependency-graph.mmd",
    "diagrams/data-area-usage.mmd": HERE / "diagrams" / "data-area-usage.mmd",
    "diagrams/event-contract.mmd": HERE / "diagrams" / "event-contract.mmd",
    "diagrams/README.md": HERE / "diagrams" / "README.md",
}

GENERATED_BANNER = (
    "Generated by `python3 fpps-hcm-modernization-deliverable/06-interface-dependency-mapping/"
    "generate_dependency_map.py` from `tools/analyze_disposition.py` and `tests/harness/source_parser.py`. "
    "**Do not edit by hand** — run the generator; `--check` fails if this file drifts."
)


def _rel(path):
    return str(Path(path).relative_to(REPO)) if Path(path).is_absolute() else str(path)


def _numbered_executable_lines(path):
    """Yield (line_no, text) for executable lines, preserving original numbering."""
    for no, raw in enumerate(sp.read_source(path).splitlines(), 1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("*") or stripped.startswith("/*"):
            continue
        code = re.split(r"/\*", raw)[0].rstrip()
        if code.strip():
            yield no, code


# --------------------------------------------------------------------------
# model
# --------------------------------------------------------------------------
def build_model():
    result = analyze()
    inv = {o["object"]: o for o in result["inventory"]}
    refs = sorted(result["references"], key=lambda r: (r["caller"], r["line"], r["callee"]))

    fan_out = defaultdict(lambda: defaultdict(int))
    fan_in = defaultdict(lambda: defaultdict(int))
    for r in refs:
        fan_out[r["caller"]][r["statement"]] += 1
        fan_in[r["callee"]][r["statement"]] += 1

    # external touch-points scanned from executable lines of code objects
    work, content, page = [], [], []
    for name, o in sorted(inv.items()):
        if o["type"] not in CODE_TYPES:
            continue
        for no, code in _numbered_executable_lines(REPO / o["path"]):
            m = _WORK_RE.match(code)
            if m:
                work.append((name, o["path"], no, code.strip()))
            if _XCI_RE.search(code) and not re.match(r"^\s*\d+\s+XCIOBJECTS", code):
                content.append((name, o["path"], no, code.strip()))
            m = _PAGE_RE.match(code)
            if m and not m.group(1).upper().startswith("PROCESS PAGE UPDATE"):
                page.append((name, o["path"], no, code.strip()))

    # NJX event contract: page declarations (xml line) vs adapter handlers (NSP line)
    xml_lines = sp.read_source(UI_XML).splitlines()
    declared = defaultdict(list)
    for no, line in enumerate(xml_lines, 1):
        for m in _XML_METHOD_RE.finditer(line):
            declared[m.group(1)].append(no)
    adapter_path = REPO / inv[UI_ROOT]["path"]
    handlers = {}
    handler_lines = list(_numbered_executable_lines(adapter_path))
    subroutine_calls = defaultdict(list)   # subroutine -> [(callee, statement, line)]
    current_sub = None
    for no, code in handler_lines:
        m = _SUBROUTINE_RE.match(code)
        if m:
            current_sub = m.group(1).upper()
        if re.match(r"^\s*END-SUBROUTINE", code, re.I):
            current_sub = None
        if current_sub:
            for cm in _CALLNAT_RE.finditer(code):
                subroutine_calls[current_sub].append((cm.group(1).upper(), "CALLNAT", no))
            for fm in _FETCH_RE.finditer(code):
                subroutine_calls[current_sub].append((fm.group(1).upper(), "FETCH", no))
    # handler blocks: VALUE U'event' ... until next VALUE / NONE / END-DECIDE
    i = 0
    while i < len(handler_lines):
        no, code = handler_lines[i]
        m = _EVENT_HANDLER_RE.search(code)
        if m and code.strip().upper().startswith("VALUE"):
            event = m.group(1)
            performs, direct = [], []
            j = i + 1
            while j < len(handler_lines):
                n2, c2 = handler_lines[j]
                if re.match(r"^\s*(VALUE\s|NONE\b|END-DECIDE)", c2, re.I):
                    break
                pm = _PERFORM_RE.match(c2)
                if pm:
                    performs.append(pm.group(1).upper())
                for cm in _CALLNAT_RE.finditer(c2):
                    direct.append((cm.group(1).upper(), "CALLNAT", n2))
                for fm in _FETCH_RE.finditer(c2):
                    direct.append((fm.group(1).upper(), "FETCH", n2))
                j += 1
            reached = list(direct)
            for s in performs:
                reached.extend(subroutine_calls.get(s, []))
            handlers[event] = {"line": no, "performs": performs, "reached": reached, "direct": direct}
            i = j
            continue
        i += 1

    events = []
    for ev in sorted(set(declared) | set(handlers)):
        h = handlers.get(ev) or handlers.get("lines." + ev)
        events.append({
            "event": ev,
            "xml_lines": declared.get(ev, []),
            "adapter_line": h["line"] if h else None,
            "performs": h["performs"] if h else [],
            "reached": sorted({(c, s) for c, s, _ in h["reached"]}) if h else [],
            "direct": sorted({(c, s) for c, s, _ in h["direct"]}) if h else [],
        })

    return {
        "result": result, "inv": inv, "refs": refs, "fan_in": fan_in, "fan_out": fan_out,
        "work": work, "content": content, "page": page, "events": events,
        "subroutine_calls": {s: sorted({(c, st) for c, st, _ in v}) for s, v in subroutine_calls.items()},
        "adapter_path": _rel(adapter_path), "xml_path": _rel(UI_XML), "xml_lines": len(xml_lines),
    }


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------
def _md_table(headers, rows):
    L = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        L.append("| " + " | ".join(str(c) for c in r) + " |")
    return L


def _c(s):
    return f"`{s}`"


def _nid(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def render_dependency_map(m):
    inv, refs, ct = m["inv"], m["refs"], m["result"]["control_totals"]
    stmt_counts = defaultdict(int)
    for r in refs:
        stmt_counts[r["statement"]] += 1
    L = ["# Dependency map (generated)", "", GENERATED_BANNER, "",
         "> Every edge is a *static literal* reference found in executable source (comments removed)."
         " Dynamic invocations (`CALLNAT #VAR`) are counted separately because static analysis cannot resolve"
         " them. Maturity: **Demonstrated** — regenerated from the shipped sources on each run; nothing here"
         " asserts runtime behaviour.", "",
         "## Edge totals", ""]
    L += _md_table(["Measure", "Value"], [
        ("Static edges (all statement types)", ct["static_references"]),
        *[(f"… {s}", stmt_counts[s]) for s in STATEMENT_ORDER],
        ("Dynamic invocations (unresolvable statically)", ct["dynamic_invocations"]),
        ("Distinct callers", len({r["caller"] for r in refs})),
        ("Distinct callees", len({r["callee"] for r in refs})),
        ("Objects with no inbound edge (unreferenced in analyzed scope)", ", ".join(_c(o) for o in ct["unreferenced_objects"]) or "none"),
        ("Stand-alone programs with no UI path", ", ".join(_c(o) for o in ct["standalone_programs_no_ui_path"]) or "none"),
    ])

    L += ["", "## Full edge list", "",
          "Ordered by caller, then source line. `Callee type` comes from the object inventory; the line is the"
          " physical line in the caller's source file.", ""]
    L += _md_table(["#", "Caller", "Caller library", "Statement", "Callee", "Callee type", "Callee library", "Source line"],
                   [(i, _c(r["caller"]), inv[r["caller"]]["library"], r["statement"], _c(r["callee"]),
                     inv[r["callee"]]["type"], inv[r["callee"]]["library"],
                     _c(f"{inv[r['caller']]['path']}:{r['line']}"))
                    for i, r in enumerate(refs, 1)])

    L += ["", "## Fan-out per caller", ""]
    L += _md_table(["Caller", "Type", *STATEMENT_ORDER, "Total"],
                   [(_c(c), inv[c]["type"], *[m["fan_out"][c][s] for s in STATEMENT_ORDER], sum(m["fan_out"][c].values()))
                    for c in sorted(m["fan_out"])])
    L += ["", "## Fan-in per callee", ""]
    L += _md_table(["Callee", "Type", *STATEMENT_ORDER, "Total", "Distinct callers"],
                   [(_c(c), inv[c]["type"], *[m["fan_in"][c][s] for s in STATEMENT_ORDER], sum(m["fan_in"][c].values()),
                     ", ".join(_c(x) for x in sorted({r["caller"] for r in refs if r["callee"] == c})))
                    for c in sorted(m["fan_in"])])

    L += ["", "## Cross-library edges (RDCRUISE → CRUISE16)", "",
          "These are the only places the presentation library depends on the business-logic library; they are the"
          " service contract an HCM integration layer replaces.", ""]
    L += _md_table(["Caller", "Statement", "Callee", "Callee type", "Source line"],
                   [(_c(r["caller"]), r["statement"], _c(r["callee"]), inv[r["callee"]]["type"],
                     _c(f"{inv[r['caller']]['path']}:{r['line']}"))
                    for r in refs if inv[r["caller"]]["library"] == "RDCRUISE" and inv[r["callee"]]["library"] == "CRUISE16"])

    L += ["", "## External touch-points", "",
          "Everything below leaves the Natural object graph: files on disk, content objects handed to the browser,"
          " and the page contract. Scanned from executable lines only.", "",
          "### Work files", ""]
    L += _md_table(["Object", "Statement (executable line)", "Source line"],
                   [(_c(o), _c(code), _c(f"{p}:{no}")) for o, p, no, code in m["work"]])
    L += ["", "### Content objects (`XCIOBJECTS` → `nat:` URLs)", ""]
    L += _md_table(["Object", "Statement (executable line)", "Source line"],
                   [(_c(o), _c(code), _c(f"{p}:{no}")) for o, p, no, code in m["content"]])
    L += ["", "### Page processing statements", ""]
    L += _md_table(["Object", "Statement (executable line)", "Source line"],
                   [(_c(o), _c(code), _c(f"{p}:{no}")) for o, p, no, code in m["page"]])

    declared_only = [e for e in m["events"] if e["xml_lines"] and e["adapter_line"] is None]
    adapter_only = [e for e in m["events"] if not e["xml_lines"] and e["adapter_line"] is not None]
    both = [e for e in m["events"] if e["xml_lines"] and e["adapter_line"] is not None]
    L += ["", f"### NJX event contract (`{m['xml_path']}` ↔ `{m['adapter_path']}`)", "",
          f"The page ({m['xml_lines']} lines) declares events through `method=\"…\"` attributes; the adapter handles them in a"
          f" `DECIDE ON FIRST *PAGE-EVENT` block. Services reached = literal CALLNAT/FETCH inside the handler block or inside"
          f" the subroutines it PERFORMs.", ""]
    L += _md_table(["Measure", "Value"], [
        ("Events declared in the page", len([e for e in m["events"] if e["xml_lines"]])),
        ("Declared events handled in the adapter", len(both)),
        ("Declared events with no adapter handler", ", ".join(_c(e["event"]) for e in declared_only) or "none"),
        ("Adapter handlers with no page declaration (static candidates)", ", ".join(_c(e["event"]) for e in adapter_only) or "none"),
    ])
    L += ["", "#### Declared events and their handlers", ""]
    L += _md_table(["Event", "Page line(s)", "Adapter handler line", "PERFORMs", "Services reached (statement)"],
                   [(_c(e["event"]), ", ".join(str(n) for n in e["xml_lines"]),
                     e["adapter_line"] if e["adapter_line"] is not None else "—",
                     ", ".join(_c(s) for s in e["performs"]) or "—",
                     ", ".join(f"`{c}` ({s})" for c, s in e["reached"]) or "—")
                    for e in both + declared_only])
    L += ["", "#### Adapter handlers without a page declaration", "",
          "Evidence class: declared in adapter, not raised by any control in the analyzed page. Candidates for retirement"
          " pending SME confirmation; static analysis does not prove they are never raised.", ""]
    L += _md_table(["Handler value", "Adapter line", "PERFORMs", "Services reached (statement)"],
                   [(_c(e["event"]), e["adapter_line"], ", ".join(_c(s) for s in e["performs"]) or "—",
                     ", ".join(f"`{c}` ({s})" for c, s in e["reached"]) or "—") for e in adapter_only])
    return "\n".join(L) + "\n"


def _candidate_class(m, names):
    ct = m["result"]["control_totals"]
    cands = [n for n in names if n in ct["unreferenced_objects"] or n in ct["standalone_programs_no_ui_path"]]
    L = ["  classDef candidate stroke-dasharray: 5 5,stroke:#b00,color:#b00;"]
    if cands:
        L.append("  class " + ",".join(_nid(c) for c in cands) + " candidate;")
    return L


def render_dependency_graph(m):
    inv, refs = m["inv"], m["refs"]
    L = ["%% Generated by generate_dependency_map.py — CALLNAT / FETCH / INCLUDE edges (Demonstrated)", "flowchart LR"]
    shown = []
    for lib in ("RDCRUISE", "CRUISE16"):
        L.append(f'  subgraph {lib}["{lib} (Demonstrated)"]')
        for t in ("program", "subprogram", "copycode"):
            for n, o in sorted(inv.items()):
                if o["library"] == lib and o["type"] == t:
                    shape = ("[[", "]]") if t == "copycode" else ("[", "]")
                    L.append(f'    {_nid(n)}{shape[0]}"{n}<br/>{t}"{shape[1]}')
                    shown.append(n)
        L.append("  end")
    grouped = defaultdict(list)
    for r in refs:
        if r["statement"] != "USING":
            grouped[(r["caller"], r["callee"], r["statement"])].append(r["line"])
    for (caller, callee, stmt), lines in sorted(grouped.items(), key=lambda kv: (kv[0][0], min(kv[1]))):
        lines = sorted(lines)
        label = f"{stmt} L{lines[0]}" if len(lines) == 1 else f"{stmt} ×{len(lines)} L" + ",".join(str(n) for n in lines)
        arrow = "-.-o" if stmt == "INCLUDE" else "-->"
        L.append(f'  {_nid(caller)} {arrow}|{label}| {_nid(callee)}')
    L += _candidate_class(m, shown)
    return "\n".join(L) + "\n"


def render_data_area_usage(m):
    inv, refs = m["inv"], m["refs"]
    L = ["%% Generated by generate_dependency_map.py — USING edges (Demonstrated)", "flowchart LR"]
    callers = sorted({r["caller"] for r in refs if r["statement"] == "USING"})
    areas = [n for n, o in sorted(inv.items(), key=lambda kv: (kv[1]["library"], kv[1]["type"], kv[0]))
             if "data area" in o["type"]]
    L.append('  subgraph code["Code objects (Demonstrated)"]')
    for n in callers:
        L.append(f'    {_nid(n)}["{n}<br/>{inv[n]["library"]}"]')
    L.append("  end")
    for lib in ("RDCRUISE", "CRUISE16"):
        L.append(f'  subgraph {lib}_areas["{lib} data areas (Demonstrated)"]')
        for n in areas:
            if inv[n]["library"] == lib:
                L.append(f'    {_nid(n)}[/"{n}<br/>{inv[n]["type"]}"/]')
        L.append("  end")
    for r in refs:
        if r["statement"] == "USING":
            L.append(f'  {_nid(r["caller"])} -.->|L{r["line"]}| {_nid(r["callee"])}')
    L += _candidate_class(m, callers + areas)
    return "\n".join(L) + "\n"


def render_event_contract(m):
    L = ["%% Generated by generate_dependency_map.py — NJX page events → adapter → services (Demonstrated)",
         "flowchart LR",
         f'  subgraph page["{Path(m["xml_path"]).name} — declared events (Demonstrated)"]']
    for e in m["events"]:
        if e["xml_lines"]:
            L.append(f'    ev_{_nid(e["event"])}(["{e["event"]}"])')
    L.append("  end")
    L.append(f'  subgraph adapter["{UI_ROOT} handlers (Demonstrated)"]')
    subs = sorted({s for e in m["events"] for s in e["performs"]})
    for s in subs:
        L.append(f'    sub_{_nid(s)}["PERFORM {s}"]')
    L.append(f'    direct["inline handler logic"]')
    L.append("  end")
    L.append('  subgraph services["Services reached"]')
    svcs = sorted({c for e in m["events"] for c, _ in e["reached"]})
    for s in svcs:
        L.append(f'    svc_{_nid(s)}["{s}"]')
    L.append("  end")
    for e in m["events"]:
        if not e["xml_lines"] or e["adapter_line"] is None:
            continue
        if e["performs"]:
            for s in e["performs"]:
                L.append(f'  ev_{_nid(e["event"])} -->|L{e["adapter_line"]}| sub_{_nid(s)}')
        elif not e["direct"]:
            L.append(f'  ev_{_nid(e["event"])} -->|L{e["adapter_line"]}| direct')
        for c, st in e["direct"]:
            L.append(f'  ev_{_nid(e["event"])} ==>|{st} inline| svc_{_nid(c)}')
    for s in subs:
        for c, st in m["subroutine_calls"].get(s, []):
            L.append(f'  sub_{_nid(s)} -->|{st}| svc_{_nid(c)}')
    return "\n".join(L) + "\n"


def render_diagrams_readme(m, dep, dau, ev):
    exports = [f"{stem}{ext}" for stem in ("dependency-graph", "data-area-usage", "event-contract") for ext in (".svg", ".png")
               if (HERE / "diagrams" / f"{stem}{ext}").exists()]
    authored = [f"{stem}{ext}" for stem in ("steplib-chain", "environment-promotion", "fpps-interface-model")
                for ext in (".mmd", ".svg", ".png") if (HERE / "diagrams" / f"{stem}{ext}").exists()]
    L = ["# Diagrams (generated)", "", GENERATED_BANNER, "",
         "The three generated diagrams are **Demonstrated** (rendered from analyzer output). Dashed red nodes are static"
         " candidates (unreferenced in analyzed scope or no UI path), not assertions of runtime deadness."
         " Hand-authored diagrams for STEPLIB chaining, environment promotion and the FPPS interface model are"
         " embedded in `../deployment-config.md` and `../fpps-interface-model.md`; their Mermaid source and exports"
         " are copied here as `steplib-chain`, `environment-promotion` and `fpps-interface-model` when a renderer was"
         " available. The FPPS interface model diagram is labelled Roadmap on its right-hand side.", ""]
    if exports:
        L += ["Exported images (generated diagrams): " + ", ".join(f"`{e}`" for e in exports) + ".", ""]
    if authored:
        L += ["Authored diagram files: " + ", ".join(f"`{e}`" for e in authored) + ".", ""]
    L += ["## Dependency graph — CALLNAT / FETCH / INCLUDE (`dependency-graph.mmd`)", "", "```mermaid", dep.rstrip(), "```", "",
          "## Data-area usage — USING (`data-area-usage.mmd`)", "", "```mermaid", dau.rstrip(), "```", "",
          "## NJX event contract (`event-contract.mmd`)", "", "```mermaid", ev.rstrip(), "```", ""]
    return "\n".join(L)


def render_all():
    m = build_model()
    dep = render_dependency_graph(m)
    dau = render_data_area_usage(m)
    ev = render_event_contract(m)
    return {
        "dependency-map.md": render_dependency_map(m),
        "diagrams/dependency-graph.mmd": dep,
        "diagrams/data-area-usage.mmd": dau,
        "diagrams/event-contract.mmd": ev,
        "diagrams/README.md": render_diagrams_readme(m, dep, dau, ev),
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if committed outputs differ from a fresh render")
    args = ap.parse_args(argv)
    rendered = render_all()
    if args.check:
        drift = [str(OUTPUTS[k].relative_to(REPO)) for k, t in rendered.items()
                 if not OUTPUTS[k].exists() or OUTPUTS[k].read_text(encoding="utf-8") != t]
        if drift:
            print("DRIFT: regenerate with generate_dependency_map.py:\n  " + "\n  ".join(drift))
            return 1
        print("OK: 06-interface-dependency-mapping generated outputs are current")
        return 0
    for k, t in rendered.items():
        OUTPUTS[k].parent.mkdir(parents=True, exist_ok=True)
        OUTPUTS[k].write_text(t, encoding="utf-8")
        print("wrote", OUTPUTS[k].relative_to(REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
