#!/usr/bin/env python3
"""Equivalence reconciliation harness: legacy expected batch vs HCM output.

VALIDATION HARNESS ONLY. This Python compares an HCM's output for a synthetic
transaction batch against the outcomes the legacy Natural logic produces for
the same batch (generated by harness/legacy_batch.py from the behavioural
model in tests/harness/natural_model.py). It is not a re-implementation of
any Natural module and is not a rewrite target; the implementation target is
the HCM configuration the SI builds from directories 02-07.

Usage (run from the repository root):

  python3 <dir>/harness/reconcile.py generate-expected --out FILE.json
  python3 <dir>/harness/reconcile.py make-fixtures
  python3 <dir>/harness/reconcile.py reconcile --expected FILE.json \
          --hcm HCM-OUTPUT.(csv|json) --out REPORT-DIR [--decimals 2] \
          [--tolerance-cents 0]
  python3 <dir>/harness/reconcile.py run-all      # regenerate committed output
  python3 <dir>/harness/reconcile.py --check      # exit 1 if committed output
                                                  # differs from a fresh run

Exit codes: 0 reconciled with zero exceptions (or --check clean);
1 exceptions found (or --check drift); 2 the HCM file failed layout
validation.

HCM output layout (CSV, header row required, columns exactly as listed):

  TXN_ID,CUSTOMER_ID,CRUISE_ID,BOOKING_DATE,OUTCOME,MESSAGE_CODE,
  CONTRACT_ID,PRICE,AVAILABILITY_AFTER

JSON layout: {"batch_id": str, "records": [ {"txn_id", "customer_id",
"cruise_id", "booking_date", "outcome", "message_code", "contract_id",
"price", "availability_after"}, ... ]}. Field rules are in
equivalence-approach.md and enforced by `load_hcm_output`.
"""

import argparse
import csv
import filecmp
import io
import json
import os
import re
import shutil
import sys
import tempfile
from decimal import Decimal, InvalidOperation

HERE = os.path.abspath(os.path.dirname(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import legacy_batch as lb  # noqa: E402

HARNESS_VERSION = "1.0"
DIR_ROOT = os.path.abspath(os.path.join(HERE, ".."))
FIXTURES_DIR = os.path.join(HERE, "fixtures")
SAMPLE_OUTPUT_DIR = os.path.join(DIR_ROOT, "sample-output")
EXPECTED_PATH = os.path.join(SAMPLE_OUTPUT_DIR, "legacy-expected.json")

HCM_COLUMNS = ["TXN_ID", "CUSTOMER_ID", "CRUISE_ID", "BOOKING_DATE",
               "OUTCOME", "MESSAGE_CODE", "CONTRACT_ID", "PRICE",
               "AVAILABILITY_AFTER"]
JSON_KEYS = [c.lower() for c in HCM_COLUMNS]
OUTCOMES = {lb.ACCEPTED, lb.REJECTED}
TXN_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,32}$")
INPUT_RE = re.compile(r"^[A-Za-z0-9 ]{0,8}$")
MAX_RECORDS = 1_000_000
MAX_FILE_BYTES = 256 * 1024 * 1024


class LayoutError(Exception):
    """The HCM output file violates the documented layout."""


# ---------------------------------------------------------------------------
# HCM output loading and validation
# ---------------------------------------------------------------------------

def _int_or_none(value, field, row_no, lo, hi):
    if value is None or str(value).strip() == "":
        return None
    text = str(value).strip()
    if not re.fullmatch(r"-?\d{1,10}", text):
        raise LayoutError(f"row {row_no}: {field} '{text}' is not an integer")
    number = int(text)
    if not lo <= number <= hi:
        raise LayoutError(
            f"row {row_no}: {field} {number} outside {lo}..{hi}")
    return number


def _decimal_or_none(value, field, row_no):
    if value is None or str(value).strip() == "":
        return None
    text = str(value).strip()
    if not re.fullmatch(r"-?\d{1,10}(\.\d{1,3})?", text):
        raise LayoutError(
            f"row {row_no}: {field} '{text}' is not a decimal with at most "
            "10 integer and 3 fraction digits (DDM PRICE is P 10.3)")
    try:
        return Decimal(text)
    except InvalidOperation as exc:  # pragma: no cover - regex guards this
        raise LayoutError(f"row {row_no}: {field} '{text}' invalid") from exc


def _normalise_record(raw, row_no):
    txn_id = str(raw.get("txn_id", "")).strip()
    if not TXN_ID_RE.match(txn_id):
        raise LayoutError(
            f"row {row_no}: TXN_ID '{txn_id}' must match {TXN_ID_RE.pattern}")
    customer_id = str(raw.get("customer_id", "") or "")
    cruise_id = str(raw.get("cruise_id", "") or "")
    for field, value in (("CUSTOMER_ID", customer_id),
                         ("CRUISE_ID", cruise_id)):
        if not INPUT_RE.match(value):
            raise LayoutError(
                f"row {row_no}: {field} '{value}' must be 0-8 alphanumeric "
                "characters (A8 input parameter)")
    outcome = str(raw.get("outcome", "")).strip().upper()
    if outcome not in OUTCOMES:
        raise LayoutError(
            f"row {row_no}: OUTCOME '{outcome}' not in {sorted(OUTCOMES)}")
    message_code = _int_or_none(raw.get("message_code"), "MESSAGE_CODE",
                                row_no, 0, 9999)
    if message_code is None:
        raise LayoutError(f"row {row_no}: MESSAGE_CODE is required")
    return {
        "txn_id": txn_id,
        "customer_id": customer_id,
        "cruise_id": cruise_id,
        "booking_date": _int_or_none(raw.get("booking_date"), "BOOKING_DATE",
                                     row_no, 19000101, 99991231),
        "outcome": outcome,
        "message_code": message_code,
        "contract_id": _int_or_none(raw.get("contract_id"), "CONTRACT_ID",
                                    row_no, 0, 999999),
        "price": _decimal_or_none(raw.get("price"), "PRICE", row_no),
        "availability_after": _int_or_none(raw.get("availability_after"),
                                           "AVAILABILITY_AFTER", row_no,
                                           0, 9),
    }


def load_hcm_output(path):
    """Load and validate an HCM output file (CSV or JSON) into records."""
    if os.path.getsize(path) > MAX_FILE_BYTES:
        raise LayoutError("HCM output file exceeds the size limit")
    ext = os.path.splitext(path)[1].lower()
    raw_rows = []
    with open(path, "r", encoding="utf-8", newline="") as fh:
        if ext == ".csv":
            reader = csv.reader(fh)
            header = next(reader, None)
            if header != HCM_COLUMNS:
                raise LayoutError(
                    f"CSV header must be exactly {','.join(HCM_COLUMNS)}")
            for row_no, row in enumerate(reader, start=2):
                if not row:
                    continue
                if len(row) != len(HCM_COLUMNS):
                    raise LayoutError(
                        f"row {row_no}: expected {len(HCM_COLUMNS)} columns, "
                        f"got {len(row)}")
                raw_rows.append(dict(zip(JSON_KEYS, row)))
        elif ext == ".json":
            payload = json.load(fh)
            if not isinstance(payload, dict) or "records" not in payload:
                raise LayoutError("JSON must be an object with 'records'")
            if not isinstance(payload["records"], list):
                raise LayoutError("'records' must be a list")
            for row_no, rec in enumerate(payload["records"], start=1):
                if not isinstance(rec, dict):
                    raise LayoutError(f"record {row_no} is not an object")
                unknown = set(rec) - set(JSON_KEYS)
                if unknown:
                    raise LayoutError(
                        f"record {row_no}: unknown keys {sorted(unknown)}")
                raw_rows.append(rec)
        else:
            raise LayoutError("HCM output must be a .csv or .json file")
    if len(raw_rows) > MAX_RECORDS:
        raise LayoutError("HCM output exceeds the record limit")
    records = [_normalise_record(r, i + 1) for i, r in enumerate(raw_rows)]
    seen = set()
    for rec in records:
        if rec["txn_id"] in seen:
            raise LayoutError(f"TXN_ID {rec['txn_id']} occurs more than once")
        seen.add(rec["txn_id"])
    return records


# ---------------------------------------------------------------------------
# Reconciliation
# ---------------------------------------------------------------------------

def _expected_view(expected):
    """Project the legacy expected batch onto the HCM output field names."""
    view = []
    for r in expected["records"]:
        view.append({
            "txn_id": r["txn_id"],
            "customer_id": r["customer_in"],
            "cruise_id": r["cruise_in"],
            "booking_date": r["booking_date"],
            "outcome": r["outcome"],
            "message_code": r["msg_nr"],
            "contract_id": r["contract_id"],
            "price": Decimal(r["price"]) if r["price"] is not None else None,
            "availability_after": r["availability_after"],
        })
    return view


def _fmt(value, decimals=None):
    if value is None:
        return ""
    if isinstance(value, Decimal) and decimals is not None:
        return str(lb.cents(value, decimals))
    return str(value)


def _totals(records, decimals):
    accepted = [r for r in records if r["outcome"] == lb.ACCEPTED]
    by_msg = {}
    for r in records:
        key = str(r["message_code"])
        by_msg[key] = by_msg.get(key, 0) + 1
    price_sum = sum((lb.cents(r["price"], decimals) for r in accepted
                     if r["price"] is not None), Decimal(0))
    ids = [r["contract_id"] for r in accepted if r["contract_id"] is not None]
    accepted_per_cruise = {}
    for r in accepted:
        key = r["cruise_id"].strip()
        accepted_per_cruise[key] = accepted_per_cruise.get(key, 0) + 1
    return {
        "record_count": len(records),
        "accepted_count": len(accepted),
        "rejected_count": len(records) - len(accepted),
        "count_by_msg_nr": dict(sorted(by_msg.items())),
        "price_sum": str(lb.cents(price_sum, decimals)),
        "contract_id_count": len(ids),
        "distinct_contract_id_count": len(set(ids)),
        "accepted_per_cruise": dict(sorted(accepted_per_cruise.items())),
    }


def reconcile(expected, hcm_records, decimals=2, tolerance_cents=0):
    """Compare the HCM output with the legacy expected batch.

    Returns (summary, audit_rows, exceptions). Every expected transaction
    gets one audit row; every finding gets one exception row with a check
    identifier documented in equivalence-approach.md.
    """
    exp_rows = _expected_view(expected)
    exp_by_id = {r["txn_id"]: r for r in exp_rows}
    act_by_id = {r["txn_id"]: r for r in hcm_records}
    tolerance = Decimal(tolerance_cents).scaleb(-2)
    exceptions = []
    audit = []

    def add_exc(check, txn_id, field, expected_v, actual_v, detail):
        exceptions.append({
            "check": check,
            "txn_id": txn_id,
            "field": field,
            "expected": expected_v,
            "actual": actual_v,
            "detail": detail,
        })

    # -- control totals ----------------------------------------------------
    exp_totals = expected["control_totals"]
    act_totals = _totals(hcm_records, decimals)
    exp_price_sum = Decimal(exp_totals["price_sum"])
    act_price_sum = Decimal(act_totals["price_sum"])
    ct = [
        ("CT-01", "record_count", exp_totals["record_count"],
         act_totals["record_count"]),
        ("CT-02", "accepted_count", exp_totals["accepted_count"],
         act_totals["accepted_count"]),
        ("CT-02", "rejected_count", exp_totals["rejected_count"],
         act_totals["rejected_count"]),
    ]
    for check, field, e, a in ct:
        if e != a:
            add_exc(check, "*", field, str(e), str(a),
                    f"batch {field} differs by {a - e:+d}")
    codes = sorted(set(exp_totals["count_by_msg_nr"])
                   | set(act_totals["count_by_msg_nr"]), key=int)
    for code in codes:
        e = exp_totals["count_by_msg_nr"].get(code, 0)
        a = act_totals["count_by_msg_nr"].get(code, 0)
        if e != a:
            add_exc("CT-03", "*", f"count_by_msg_nr[{code}]", str(e), str(a),
                    f"message code {code} occurrences differ by {a - e:+d}")
    if abs(act_price_sum - exp_price_sum) > tolerance:
        diff_cents = int(((act_price_sum - exp_price_sum) * 100)
                         .to_integral_value())
        add_exc("CT-04", "*", "price_sum", str(exp_price_sum),
                str(act_price_sum),
                f"sum of PRICE over accepted records differs by "
                f"{diff_cents:+d} cent(s)")
    if act_totals["distinct_contract_id_count"] != act_totals[
            "contract_id_count"]:
        add_exc("CT-05", "*", "distinct_contract_id_count",
                str(act_totals["contract_id_count"]),
                str(act_totals["distinct_contract_id_count"]),
                "CONTRACT_ID values in the HCM output are not unique")
    before = expected["availability_before"]
    exp_delta = exp_totals["availability_delta"]
    for cruise in sorted(before, key=int):
        e_delta = exp_delta[cruise]
        a_delta = -act_totals["accepted_per_cruise"].get(cruise, 0)
        if e_delta != a_delta:
            add_exc("CT-06", "*", f"availability_delta[{cruise}]",
                    str(e_delta), str(a_delta),
                    f"cruise {cruise}: accepted bookings imply availability "
                    f"delta {a_delta:+d}, legacy {e_delta:+d}")

    # -- record level --------------------------------------------------------
    field_checks = [
        ("RL-03", "outcome"),
        ("RL-04", "message_code"),
        ("RL-05", "contract_id"),
        ("RL-06", "price"),
        ("RL-07", "availability_after"),
    ]
    for txn_id in sorted(exp_by_id):
        e = exp_by_id[txn_id]
        a = act_by_id.get(txn_id)
        row = {
            "txn_id": txn_id,
            "customer_id": e["customer_id"],
            "cruise_id": e["cruise_id"],
            "expected_outcome": e["outcome"],
            "expected_message_code": e["message_code"],
            "expected_contract_id": _fmt(e["contract_id"]),
            "expected_price": _fmt(e["price"], decimals),
            "expected_availability_after": _fmt(e["availability_after"]),
        }
        if a is None:
            row.update({
                "actual_outcome": "", "actual_message_code": "",
                "actual_contract_id": "", "actual_price": "",
                "actual_availability_after": "", "price_diff_cents": "",
                "status": "MISSING", "checks_failed": "RL-01",
            })
            add_exc("RL-01", txn_id, "record", "present", "absent",
                    f"transaction {txn_id} (customer '{e['customer_id']}', "
                    f"cruise '{e['cruise_id']}') absent from HCM output")
            audit.append(row)
            continue
        failed = []
        for check, field in field_checks:
            ev, av = e[field], a[field]
            if field == "price":
                if ev is None and av is None:
                    continue
                if ev is None or av is None:
                    failed.append(check)
                    add_exc(check, txn_id, field, _fmt(ev, decimals),
                            _fmt(av, decimals),
                            "PRICE present on one side only")
                    continue
                diff = lb.cents(av, decimals) - lb.cents(ev, decimals)
                if abs(diff) > tolerance:
                    failed.append(check)
                    diff_cents = int((diff * 100).to_integral_value())
                    add_exc(check, txn_id, field, _fmt(ev, decimals),
                            _fmt(av, decimals),
                            f"PRICE differs by {diff_cents:+d} cent(s)")
            elif ev != av:
                failed.append(check)
                add_exc(check, txn_id, field, _fmt(ev), _fmt(av),
                        f"{field} differs")
        price_diff = ""
        if e["price"] is not None and a["price"] is not None:
            price_diff = str(int(((lb.cents(a["price"], decimals)
                                   - lb.cents(e["price"], decimals)) * 100)
                                 .to_integral_value()))
        row.update({
            "actual_outcome": a["outcome"],
            "actual_message_code": a["message_code"],
            "actual_contract_id": _fmt(a["contract_id"]),
            "actual_price": _fmt(a["price"], decimals),
            "actual_availability_after": _fmt(a["availability_after"]),
            "price_diff_cents": price_diff,
            "status": "MATCH" if not failed else "MISMATCH",
            "checks_failed": ";".join(failed),
        })
        audit.append(row)
    for txn_id in sorted(set(act_by_id) - set(exp_by_id)):
        a = act_by_id[txn_id]
        add_exc("RL-02", txn_id, "record", "absent", "present",
                f"transaction {txn_id} in HCM output has no legacy "
                "counterpart")
        audit.append({
            "txn_id": txn_id, "customer_id": a["customer_id"],
            "cruise_id": a["cruise_id"], "expected_outcome": "",
            "expected_message_code": "", "expected_contract_id": "",
            "expected_price": "", "expected_availability_after": "",
            "actual_outcome": a["outcome"],
            "actual_message_code": a["message_code"],
            "actual_contract_id": _fmt(a["contract_id"]),
            "actual_price": _fmt(a["price"], decimals),
            "actual_availability_after": _fmt(a["availability_after"]),
            "price_diff_cents": "", "status": "UNEXPECTED",
            "checks_failed": "RL-02",
        })

    # -- cross-record integrity ----------------------------------------------
    owners = {}
    for r in hcm_records:
        if r["outcome"] == lb.ACCEPTED and r["contract_id"] is not None:
            owners.setdefault(r["contract_id"], []).append(r["txn_id"])
    pre_existing = set(expected["pre_existing_contract_ids"])
    for contract_id in sorted(owners):
        txns = owners[contract_id]
        if len(txns) > 1:
            add_exc("IN-01", ";".join(txns), "contract_id", "unique",
                    str(contract_id),
                    f"CONTRACT_ID {contract_id} assigned to "
                    f"{len(txns)} transactions")
        if contract_id in pre_existing:
            add_exc("IN-02", ";".join(txns), "contract_id",
                    f"> {max(pre_existing)}", str(contract_id),
                    "CONTRACT_ID collides with a contract that existed "
                    "before the batch")
    for cruise in sorted(before, key=int):
        accepted_n = act_totals["accepted_per_cruise"].get(cruise, 0)
        if accepted_n > before[cruise]:
            txns = [r["txn_id"] for r in hcm_records
                    if r["outcome"] == lb.ACCEPTED
                    and r["cruise_id"].strip() == cruise]
            add_exc("IN-03", ";".join(txns), "availability",
                    f"<= {before[cruise]} accepted", f"{accepted_n} accepted",
                    f"cruise {cruise} oversold: {accepted_n} bookings "
                    f"accepted against {before[cruise]} available")
    customer_master = {
        str(rec["PERSON-ID"])
        for rec in lb.build_db().files["NCCUSTOMER"].records.values()}
    for r in hcm_records:
        if r["outcome"] == lb.ACCEPTED and (
                r["customer_id"].strip() not in customer_master):
            add_exc("IN-04", r["txn_id"], "customer_id", "in NCCUSTOMER",
                    r["customer_id"],
                    f"booking accepted for customer '{r['customer_id']}' who "
                    "is not in the synthetic customer master")

    exceptions.sort(key=lambda x: (x["check"], x["txn_id"], x["field"]))
    summary = {
        "harness_version": HARNESS_VERSION,
        "batch_id": expected["batch_id"],
        "decimals": decimals,
        "tolerance_cents": tolerance_cents,
        "result": "RECONCILED" if not exceptions else "EXCEPTIONS",
        "exception_count": len(exceptions),
        "exceptions_by_check": _count_by(exceptions, "check"),
        "records_expected": len(exp_rows),
        "records_actual": len(hcm_records),
        "records_matched": sum(1 for r in audit if r["status"] == "MATCH"),
        "records_mismatched": sum(
            1 for r in audit if r["status"] == "MISMATCH"),
        "records_missing": sum(1 for r in audit if r["status"] == "MISSING"),
        "records_unexpected": sum(
            1 for r in audit if r["status"] == "UNEXPECTED"),
        "control_totals": {
            "legacy_expected": exp_totals,
            "hcm_output": act_totals,
            "price_sum_diff_cents": int(
                ((act_price_sum - exp_price_sum) * 100).to_integral_value()),
        },
    }
    return summary, audit, exceptions


def _count_by(rows, key):
    out = {}
    for r in rows:
        out[r[key]] = out.get(r[key], 0) + 1
    return dict(sorted(out.items()))


# ---------------------------------------------------------------------------
# Report writers (deterministic: no timestamps, stable ordering)
# ---------------------------------------------------------------------------

AUDIT_COLUMNS = [
    "txn_id", "customer_id", "cruise_id", "expected_outcome",
    "actual_outcome", "expected_message_code", "actual_message_code",
    "expected_contract_id", "actual_contract_id", "expected_price",
    "actual_price", "price_diff_cents", "expected_availability_after",
    "actual_availability_after", "status", "checks_failed",
]
EXCEPTION_COLUMNS = ["check", "txn_id", "field", "expected", "actual",
                     "detail"]
CHECK_TITLES = {
    "CT-01": "Record count", "CT-02": "Accepted / rejected counts",
    "CT-03": "Count by message code", "CT-04": "Sum of PRICE to the cent",
    "CT-05": "CONTRACT_ID uniqueness (batch)",
    "CT-06": "Availability delta per cruise",
    "RL-01": "Expected record missing", "RL-02": "Unexpected record",
    "RL-03": "Outcome", "RL-04": "Message code", "RL-05": "CONTRACT_ID",
    "RL-06": "PRICE (penny level)", "RL-07": "Availability after",
    "IN-01": "Duplicate CONTRACT_ID", "IN-02": "CONTRACT_ID collision",
    "IN-03": "Oversold cruise", "IN-04": "Accepted for unknown customer",
}


def _write_csv(path, columns, rows):
    with open(path, "w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=columns, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({c: row.get(c, "") for c in columns})


def _md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def write_report(out_dir, summary, audit, exceptions, hcm_label):
    os.makedirs(out_dir, exist_ok=True)
    lb.dump_json(summary, os.path.join(out_dir, "summary.json"))
    _write_csv(os.path.join(out_dir, "audit-trail.csv"), AUDIT_COLUMNS, audit)
    _write_csv(os.path.join(out_dir, "exceptions.csv"), EXCEPTION_COLUMNS,
               exceptions)
    ct_e = summary["control_totals"]["legacy_expected"]
    ct_a = summary["control_totals"]["hcm_output"]
    lines = [
        f"# Reconciliation report — {summary['batch_id']}",
        "",
        "Generated by `harness/reconcile.py` (validation harness, not a "
        "rewrite target). Synthetic data only.",
        "",
        f"- HCM output file: `{hcm_label}`",
        f"- Result: **{summary['result']}** "
        f"({summary['exception_count']} exception(s))",
        f"- Amount precision: {summary['decimals']} decimals, tolerance "
        f"{summary['tolerance_cents']} cent(s)",
        "",
        "## Control totals",
        "",
        _md_table(
            ["Total", "Legacy expected", "HCM output", "Status"],
            [
                ["Records", ct_e["record_count"], ct_a["record_count"],
                 _status(ct_e["record_count"] == ct_a["record_count"])],
                ["Accepted", ct_e["accepted_count"], ct_a["accepted_count"],
                 _status(ct_e["accepted_count"] == ct_a["accepted_count"])],
                ["Rejected", ct_e["rejected_count"], ct_a["rejected_count"],
                 _status(ct_e["rejected_count"] == ct_a["rejected_count"])],
                ["Sum of PRICE (accepted)", ct_e["price_sum"],
                 ct_a["price_sum"],
                 _status(summary["control_totals"]["price_sum_diff_cents"]
                         == 0)
                 + (f" ({summary['control_totals']['price_sum_diff_cents']:+d}"
                    " cent(s))"
                    if summary["control_totals"]["price_sum_diff_cents"]
                    else "")],
                ["Distinct CONTRACT_ID / assigned",
                 f"{ct_e['distinct_contract_id_count']} / "
                 f"{ct_e['contract_id_count']}",
                 f"{ct_a['distinct_contract_id_count']} / "
                 f"{ct_a['contract_id_count']}",
                 _status(ct_a["distinct_contract_id_count"]
                         == ct_a["contract_id_count"])],
            ]),
        "",
        "### Count by message code",
        "",
        _md_table(
            ["Message code", "Legacy expected", "HCM output", "Status"],
            [[code, ct_e["count_by_msg_nr"].get(code, 0),
              ct_a["count_by_msg_nr"].get(code, 0),
              _status(ct_e["count_by_msg_nr"].get(code, 0)
                      == ct_a["count_by_msg_nr"].get(code, 0))]
             for code in sorted(set(ct_e["count_by_msg_nr"])
                                | set(ct_a["count_by_msg_nr"]), key=int)]),
        "",
        "### Availability delta per cruise",
        "",
        _md_table(
            ["Cruise", "Legacy delta", "HCM delta (from accepted rows)",
             "Status"],
            [[cruise, f"{ct_e['availability_delta'][cruise]:+d}",
              f"{-ct_a['accepted_per_cruise'].get(cruise, 0):+d}",
              _status(ct_e["availability_delta"][cruise]
                      == -ct_a["accepted_per_cruise"].get(cruise, 0))]
             for cruise in sorted(ct_e["availability_delta"], key=int)]),
        "",
        "## Record-level outcome",
        "",
        _md_table(
            ["Status", "Records"],
            [["MATCH", summary["records_matched"]],
             ["MISMATCH", summary["records_mismatched"]],
             ["MISSING", summary["records_missing"]],
             ["UNEXPECTED", summary["records_unexpected"]]]),
        "",
        "Full record-level audit trail: `audit-trail.csv` "
        f"({len(audit)} rows).",
        "",
        "## Exceptions",
        "",
    ]
    if exceptions:
        lines.append(_md_table(
            ["Check", "Title", "Transaction(s)", "Field", "Expected",
             "Actual", "Detail"],
            [[x["check"], CHECK_TITLES.get(x["check"], ""), x["txn_id"],
              x["field"], x["expected"], x["actual"], x["detail"]]
             for x in exceptions]))
        lines += ["", "### Exceptions by check", "",
                  _md_table(["Check", "Title", "Count"],
                            [[c, CHECK_TITLES.get(c, ""), n] for c, n in
                             summary["exceptions_by_check"].items()])]
    else:
        lines.append("None. Every control total and every record "
                     "reconciles to zero difference.")
    lines += ["", "Machine-readable copies: `summary.json`, "
                  "`exceptions.csv`.", ""]
    with open(os.path.join(out_dir, "reconciliation-report.md"), "w",
              encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def _status(ok):
    return "reconciled" if ok else "EXCEPTION"


def write_expected_markdown(expected, path):
    """Human-readable rendering of the legacy expected batch."""
    ct = expected["control_totals"]
    rows = []
    for r in expected["records"]:
        rows.append([
            r["txn_id"], f"`{r['customer_in']}`" if r["customer_in"] else "(blank)",
            f"`{r['cruise_in']}`" if r["cruise_in"] else "(blank)",
            r["outcome"], r["msg_nr"], r["rsp_code"],
            _fmt(r["contract_id"]),
            _fmt(Decimal(r["price"]), expected["decimals"])
            if r["price"] is not None else "",
            _fmt(r["availability_after"]),
        ])
    lines = [
        f"# Legacy expected batch — {expected['batch_id']}",
        "",
        "Generated by `harness/reconcile.py run-all` from "
        f"`{expected['oracle']}` (validation harness, not a rewrite target). "
        "Synthetic data only. Machine-readable copy: `legacy-expected.json`.",
        "",
        f"- Oracle: `{expected['oracle']}`",
        f"- Cross-check: `{expected['cross_check']}`",
        f"- Fixture: `{expected['fixture']}`",
        f"- Booking date (DATE-BOOKING): {expected['booking_date']}",
        f"- Pre-existing CONTRACT-ID values: "
        f"{', '.join(str(i) for i in expected['pre_existing_contract_ids'])}",
        "",
        "## Control totals",
        "",
        _md_table(["Total", "Value"], [
            ["Records", ct["record_count"]],
            ["Accepted (contract stored)", ct["accepted_count"]],
            ["Rejected (no contract)", ct["rejected_count"]],
            ["Sum of PRICE over accepted records", ct["price_sum"]],
            ["Distinct CONTRACT-ID / assigned",
             f"{ct['distinct_contract_id_count']} / "
             f"{ct['contract_id_count']}"],
        ]),
        "",
        _md_table(["Message code", "Records"],
                  [[k, v] for k, v in ct["count_by_msg_nr"].items()]),
        "",
        _md_table(["Cruise", "Availability before", "Availability after",
                   "Delta"],
                  [[c, expected["availability_before"][c],
                    expected["availability_after"][c],
                    f"{ct['availability_delta'][c]:+d}"]
                   for c in sorted(expected["availability_before"],
                                   key=int)]),
        "",
        "## Transactions",
        "",
        _md_table(["Txn", "Customer in", "Cruise in", "Outcome",
                   "MSG-NR", "RSP-CODE", "CONTRACT-ID", "PRICE",
                   "Availability after"], rows),
        "",
    ]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


# ---------------------------------------------------------------------------
# Fixtures: clean (HCM output identical to legacy) and broken (seeded defects)
# ---------------------------------------------------------------------------

SEEDED_DEFECTS = [
    ("D1", "T-0004", "off-by-one-cent PRICE (1349.99 -> 1349.98)"),
    ("D2", "T-0018", "duplicate CONTRACT_ID (500108 -> 500107, already "
                     "assigned to T-0017)"),
    ("D3", "T-0016", "booking accepted for unavailable cruise 2201 "
                     "(legacy 9902 -> ACCEPTED 9800, CONTRACT_ID 500112)"),
    ("D4", "T-0011", "booking accepted for missing customer 99999999 "
                     "(legacy 9918 -> ACCEPTED 9800, CONTRACT_ID 500113)"),
]


def _expected_to_hcm_rows(expected, decimals):
    rows = []
    for r in _expected_view(expected):
        rows.append({
            "txn_id": r["txn_id"],
            "customer_id": r["customer_id"],
            "cruise_id": r["cruise_id"],
            "booking_date": r["booking_date"],
            "outcome": r["outcome"],
            "message_code": r["message_code"],
            "contract_id": r["contract_id"],
            "price": (str(lb.cents(r["price"], decimals))
                      if r["price"] is not None else None),
            "availability_after": r["availability_after"],
        })
    return rows


def _seed_defects(rows):
    by_id = {r["txn_id"]: r for r in rows}
    by_id["T-0004"]["price"] = "1349.98"
    by_id["T-0018"]["contract_id"] = 500107
    by_id["T-0016"].update({"outcome": lb.ACCEPTED, "message_code": 9800,
                            "contract_id": 500112, "price": "1349.99",
                            "availability_after": 0})
    by_id["T-0011"].update({"outcome": lb.ACCEPTED, "message_code": 9800,
                            "contract_id": 500113, "price": "1290.00",
                            "availability_after": 2})
    return rows


def _write_hcm_csv(path, rows):
    with open(path, "w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(HCM_COLUMNS)
        for r in rows:
            writer.writerow(["" if r[k] is None else r[k] for k in JSON_KEYS])


def make_fixtures(expected, fixtures_dir, decimals):
    os.makedirs(fixtures_dir, exist_ok=True)
    clean = _expected_to_hcm_rows(expected, decimals)
    _write_hcm_csv(os.path.join(fixtures_dir, "hcm-output-clean.csv"), clean)
    lb.dump_json({"batch_id": expected["batch_id"], "records": clean},
                 os.path.join(fixtures_dir, "hcm-output-clean.json"))
    broken = _seed_defects(_expected_to_hcm_rows(expected, decimals))
    _write_hcm_csv(os.path.join(fixtures_dir, "hcm-output-broken.csv"),
                   broken)
    with open(os.path.join(fixtures_dir, "SEEDED-DEFECTS.md"), "w",
              encoding="utf-8") as fh:
        fh.write("# Seeded defects in hcm-output-broken.csv\n\n"
                 "Generated by `harness/reconcile.py make-fixtures`. "
                 "`hcm-output-clean.csv` / `.json` are the legacy expected "
                 "batch rendered in the HCM output layout; the broken file "
                 "is the clean file with these four rows altered.\n\n")
        fh.write(_md_table(["Defect", "Transaction", "Alteration"],
                           [list(d) for d in SEEDED_DEFECTS]))
        fh.write("\n")


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def run_all(dir_root, decimals=2, tolerance_cents=0):
    """Regenerate every committed artefact under `dir_root`."""
    sample = os.path.join(dir_root, "sample-output")
    fixtures = os.path.join(dir_root, "harness", "fixtures")
    os.makedirs(sample, exist_ok=True)
    expected = lb.generate_expected(decimals)
    lb.dump_json(expected, os.path.join(sample, "legacy-expected.json"))
    write_expected_markdown(expected,
                            os.path.join(sample, "legacy-expected.md"))
    make_fixtures(expected, fixtures, decimals)
    results = {}
    for name in ("clean", "broken"):
        hcm_path = os.path.join(fixtures, f"hcm-output-{name}.csv")
        records = load_hcm_output(hcm_path)
        summary, audit, exceptions = reconcile(expected, records, decimals,
                                               tolerance_cents)
        write_report(os.path.join(sample, name), summary, audit, exceptions,
                     f"harness/fixtures/hcm-output-{name}.csv")
        results[name] = summary
    # The JSON layout must reconcile identically to the CSV layout.
    json_records = load_hcm_output(
        os.path.join(fixtures, "hcm-output-clean.json"))
    json_summary, _, _ = reconcile(expected, json_records, decimals,
                                   tolerance_cents)
    if json_summary != results["clean"]:
        raise RuntimeError("CSV and JSON layouts of the clean fixture do not "
                           "reconcile identically")
    return results


def _tree_files(root):
    out = []
    for base, _, files in os.walk(root):
        for f in files:
            out.append(os.path.relpath(os.path.join(base, f), root))
    return sorted(out)


def check(dir_root, decimals=2, tolerance_cents=0):
    """Regenerate into a temp dir and compare with committed output."""
    tmp = tempfile.mkdtemp(prefix="equivalence-check-")
    try:
        os.makedirs(os.path.join(tmp, "harness"))
        results = run_all(tmp, decimals, tolerance_cents)
        drift = []
        for rel in ("sample-output", os.path.join("harness", "fixtures")):
            fresh_root = os.path.join(tmp, rel)
            committed_root = os.path.join(dir_root, rel)
            fresh = _tree_files(fresh_root)
            committed = (_tree_files(committed_root)
                         if os.path.isdir(committed_root) else [])
            for f in sorted(set(fresh) | set(committed)):
                a = os.path.join(fresh_root, f)
                b = os.path.join(committed_root, f)
                if not (os.path.exists(a) and os.path.exists(b)
                        and filecmp.cmp(a, b, shallow=False)):
                    drift.append(os.path.join(rel, f))
        if results["clean"]["result"] != "RECONCILED":
            drift.append("clean fixture no longer reconciles to zero")
        if results["broken"]["result"] != "EXCEPTIONS":
            drift.append("broken fixture no longer raises exceptions")
        return drift
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if committed sample-output/ or "
                             "harness/fixtures/ differ from a fresh run")
    parser.add_argument("--decimals", type=int, default=2, choices=(2, 3),
                        help="amount precision for comparison (default 2)")
    parser.add_argument("--tolerance-cents", type=int, default=0,
                        help="allowed absolute amount difference in cents "
                             "(default 0: penny-level)")
    sub = parser.add_subparsers(dest="command")
    p_gen = sub.add_parser("generate-expected",
                           help="run the legacy model and write the expected "
                                "batch as JSON")
    p_gen.add_argument("--out", default=EXPECTED_PATH)
    sub.add_parser("make-fixtures",
                   help="write clean and broken HCM output fixtures")
    p_rec = sub.add_parser("reconcile",
                           help="reconcile an HCM output file against the "
                                "expected batch")
    p_rec.add_argument("--expected", default=EXPECTED_PATH)
    p_rec.add_argument("--hcm", required=True,
                       help="HCM output file (.csv or .json)")
    p_rec.add_argument("--out", required=True, help="report directory")
    sub.add_parser("run-all", help="regenerate all committed artefacts")
    args = parser.parse_args(argv)

    if args.tolerance_cents < 0 or args.tolerance_cents > 100_000:
        parser.error("--tolerance-cents must be between 0 and 100000")

    if args.check:
        drift = check(DIR_ROOT, args.decimals, args.tolerance_cents)
        if drift:
            print("DRIFT: committed equivalence output differs from a fresh "
                  "run:", file=sys.stderr)
            for item in drift:
                print(f"  {item}", file=sys.stderr)
            return 1
        print("equivalence harness: committed fixtures and sample-output are "
              "current; clean fixture reconciles to zero, broken fixture "
              "raises exceptions")
        return 0

    if args.command == "generate-expected":
        expected = lb.generate_expected(args.decimals)
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        lb.dump_json(expected, args.out)
        print(f"wrote {args.out}: {expected['control_totals']['record_count']}"
              " records")
        return 0
    if args.command == "make-fixtures":
        expected = lb.generate_expected(args.decimals)
        make_fixtures(expected, FIXTURES_DIR, args.decimals)
        print(f"wrote fixtures to {FIXTURES_DIR}")
        return 0
    if args.command == "reconcile":
        with open(args.expected, "r", encoding="utf-8") as fh:
            expected = json.load(fh)
        try:
            records = load_hcm_output(args.hcm)
        except LayoutError as exc:
            print(f"HCM output rejected: {exc}", file=sys.stderr)
            return 2
        summary, audit, exceptions = reconcile(
            expected, records, args.decimals, args.tolerance_cents)
        write_report(args.out, summary, audit, exceptions,
                     os.path.relpath(args.hcm, DIR_ROOT))
        print(f"{summary['result']}: {summary['exception_count']} "
              f"exception(s); report in {args.out}")
        return 0 if not exceptions else 1
    if args.command == "run-all":
        results = run_all(DIR_ROOT, args.decimals, args.tolerance_cents)
        for name, summary in results.items():
            print(f"{name}: {summary['result']} "
                  f"({summary['exception_count']} exception(s))")
        return 0
    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
